### ISSUE TITLE
diskquota.CacheCleanerTask Exception expiring tiles

### ISSUE THREAD

**Issue by tracyharton** [GeoWebCache/geowebcache#138]
My specified diskquota was finally reached, but now the cleaner is failing and the cache continues to grow:

16 Oct 07:39:53 WARN [diskquota.CacheCleanerTask] - Exception expiring tiles for [layer]
java.lang.NullPointerException
    at org.geowebcache.diskquota.storage.TilePageCalculator.newPagePyramid(TilePageCalculator.java:139)
    at org.geowebcache.diskquota.storage.TilePageCalculator.newPagePyramid(TilePageCalculator.java:135)
    at org.geowebcache.diskquota.storage.TilePageCalculator.getPagePyramid(TilePageCalculator.java:51)
    at org.geowebcache.diskquota.storage.TilePageCalculator.toGridCoverage(TilePageCalculator.java:69)
    at org.geowebcache.diskquota.storage.BDBQuotaStore.getTilesForPage(BDBQuotaStore.java:609)
    at org.geowebcache.diskquota.CacheCleaner.expirePage(CacheCleaner.java:214)
    at org.geowebcache.diskquota.CacheCleaner.expireByLayerNames(CacheCleaner.java:201)
    at org.geowebcache.diskquota.DiskQuotaMonitor.expireByLayerNames(DiskQuotaMonitor.java:498)
    at org.geowebcache.diskquota.CacheCleanerTask$LayerQuotaEnforcementTask.call(CacheCleanerTask.java:217)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)

**Comment by Bolivers** [comment]
Was getting the same issue but finally solved it.

I was getting the error below and once it occurred the quota system was corrupt and I'd need to rebuild the quota database.

22 Jul 21:26:01 (GWC DiskQuota clean up thread-2) WARN [diskquota.CacheCleanerTask] - Exception expiring tiles for [aerial] java.lang.ArrayIndexOutOfBoundsException: 11
        at org.geowebcache.diskquota.storage.PagePyramid.toGridCoverage(PagePyramid.java:238)

By clearing the cache and seeding one layer at a time I figured out it was only happening when it tried to clear out certain zoom levels, in my case levels 11 and above caused the error (the error above shows it on level 11, hence java.lang.ArrayIndexOutOfBoundsException: 11). I had zoom levels 0 to 15 defined and 11 to 15 were broken for me.

After much changing of settings in geowebcache.xml I finally discovered changing 			

<zoomStart>5</zoomStart> 
to 
<zoomStart>0</zoomStart> 

or removing it completely solved the problem. 

And if I set it to 4 and then level 11 worked but 12 and above didn't, set it to 3 and levels 11&12 worked... see where I'm going....

So I can only presume it's a problem with the array size being set to the number of zoom levels minus the zoomstart value (e.g. 15-5=10) and the array is then being accessed by the zoom level number (so in my case anything above 11 would break it).

zoomstart obviously has its use, but for me it was much more important to get disk quota management working again - which it now is.

**Comment by sailorsenergy** [comment]
@Bolivers . I can't thank you enough for replying with the solution. That *indeed* seemed to fix the problem and GWC is now happily truncating tiles. Thanks!!!

Just so it's clear for others, make sure the <zoomStart> is exactly consistent with what's in your geowebcache.xml <gridSet> description for your <wmsLayer>. In my case, I confused <zoomStart> for <minCachedLevel>. Here's an example of the change I made to fix the problem:
```diff
-      <zoomStart>11</zoomStart>
+      <zoomStart>0</zoomStart>
       <zoomStop>12</zoomStop>
+      <minCachedLevel>11</minCachedLevel>
```
