### ISSUE TITLE
Seeding thread dies when WMS server returns error

### ISSUE THREAD

**Issue by whatnick** [GeoWebCache/geowebcache#394]
I am attempting to seed from an Skyline SFS WMS server which at times returns errors in XML format, which causes an uncaught error leading to death of the Seeding thread. See stacktrace below:

```
23 Jun 14:45:52 (GWC Seeder Thread-12) ERROR [seed.MTSeeder] - All backends (1) failed. Reason: Responseheader advertised 511 bytes, but only received 0 from http://XXXXXXXXXXXXXXXXXXX/streamer.ashx?.  Last request: 'http://XXXXXXXXXXXXXXXXXXXXXX/streamer.ashx?'. MimeType mismatch, expected image/jpeg but got application/vnd.ogc.se_xml; charset=utf-8 from http://xxxxx/sfs.aspx?:

                                <!DOCTYPE ServiceExceptionReport SYSTEM
                                 "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
                                    <ServiceExceptionReport version='1.1.1'>
                                        <ServiceException code='NoApplicableCode'>
                                            <![CDATA[]]>
                                        </ServiceException>
                                    </ServiceExceptionReport>
org.geowebcache.GeoWebCacheException: All backends (1) failed. Reason: Responseheader advertised 511 bytes, but only received 0 from http://XXXXXXXXXXXXXXXXXX/streamer.ashx?.  Last request: 'http://XXXXXXXXXXXXXXXXXXXXXX/streamer.ashx?'. MimeType mismatch, expected image/jpeg but got application/vnd.ogc.se_xml; charset=utf-8 from http://XXXXXXXXXXXXXXXXXXXXXXXX/streamer.ashx?:

                                <!DOCTYPE ServiceExceptionReport SYSTEM
                                 "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
                                    <ServiceExceptionReport version='1.1.1'>
                                        <ServiceException code='NoApplicableCode'>
                                            <![CDATA[]]>
                                        </ServiceException>
                                    </ServiceExceptionReport>
	at org.geowebcache.layer.wms.WMSHttpHelper.makeRequest(WMSHttpHelper.java:141)
	at org.geowebcache.layer.wms.WMSSourceHelper.makeRequest(WMSSourceHelper.java:87)
	at org.geowebcache.layer.wms.WMSLayer.doNonMetatilingRequest(WMSLayer.java:512)
	at org.geowebcache.layer.wms.WMSLayer.getNonMetatilingReponse(WMSLayer.java:473)
	at org.geowebcache.layer.wms.WMSLayer.seedTile(WMSLayer.java:326)
	at org.geowebcache.seed.SeedTask.doActionInternal(SeedTask.java:136)
	at org.geowebcache.seed.GWCTask.doAction(GWCTask.java:76)
	at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:36)
	at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by smithkm** [comment]
This is really more of a question for the users mailing list. GitHub tickets are for specific bugs we've narrowed down enough to understand what needs to be fixed.

**Comment by smithkm** [comment]
Sorry, misread this while running through and clearing old tickets.

**Comment by whatnick** [comment]
No problem. Let me know if you require further details.

**Comment by smithkm** [comment]
OK, looking into the code it appears this is an intentional behaviour for backward compatibility with something (I'm not sure what). I think you should be able to resolve it by setting a system property or context parameter  'GWC_SEED_RETRY_COUNT' to a positive value.  The default 0 will abort the seed task on a failure, a positive number will try that many times before giving up, and then move on to the next tile.

**Comment by whatnick** [comment]
Thanks will test it and close the issue.
