### ISSUE TITLE
Infinite loop of ConcurrentModifcationExceptions when two instances update the Tile Quota DB

### ISSUE THREAD

**Issue by citricwage** [GeoWebCache/geowebcache#523]
Our setup consists of two GeoWebCache (standalone) instances. One is used by clients, and the other is used for seeding and maintenance via the REST API. Both share a common configuration and tile store, and use a Postgres tilequota database.

In production, we have had repeated issues where one of the instances gets stuck in an infinite loop, generating the below exception. This keeps going until the log fills up the disk (we have seen logs > 100Gb).

The root cause is that the tilequota database uses a double for the fill_factor, but the code reads it as a float. Then, we get queries like 

> update tilepage set fill_factor = 8.204E-4 where key = '<tilesetid>#image/png@74,43,13' and fill_factor = 5.047E-4; 

But the database contains 5.04700008943677E-4 for that row. So, the update fails, and is tried again - and again, and again....

To manually reproduce this, I simply ran the following in postgres: 

> update tilepage set fill_factor = fill_factor - 0.000001 where key = '<tilesetid>#image/png@74,43,13';

 and then moved my viewer to a part of that tilepage where there are no seeded tiles.

The exception is:
```
org.springframework.dao.ConcurrencyFailureException: Failed to create or update page stats for page TilePage[<tilesetid>#image/png@1,26,6] after 100 attempts        at org.geowebcache.diskquota.jdbc.JDBCQuotaStore$9.upsertTilePageFillFactor(JDBCQuotaStore.java:528)
        at org.geowebcache.diskquota.jdbc.JDBCQuotaStore$9.doInTransactionWithoutResult(JDBCQuotaStore.java:458)
        at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.geowebcache.diskquota.jdbc.JDBCQuotaStore.addToQuotaAndTileCounts(JDBCQuotaStore.java:446)
        at org.geowebcache.diskquota.QueuedQuotaUpdatesConsumer.commit(QueuedQuotaUpdatesConsumer.java:312)
        at org.geowebcache.diskquota.QueuedQuotaUpdatesConsumer.checkAggregatedTimeout(QueuedQuotaUpdatesConsumer.java:293)
        at org.geowebcache.diskquota.QueuedQuotaUpdatesConsumer.checkAggregatedTimeouts(QueuedQuotaUpdatesConsumer.java:250)
        at org.geowebcache.diskquota.QueuedQuotaUpdatesConsumer.call(QueuedQuotaUpdatesConsumer.java:198)
        at org.geowebcache.diskquota.QueuedQuotaUpdatesConsumer.call(QueuedQuotaUpdatesConsumer.java:23)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by smithkm** [comment]
It looks like this was a result of an SQL `float` being equivalent to a java `double` instead of a java `float`.

Changing the schema from `float` to `real` should fix this.  

We should probably be using a bigint of some sort to store the tile count instead of a floating point number to store the proportion of tiles but that would require changing the Quota Store API and breaking backwards compatibility with existing quota stores.  We'd also need to make sure all the back ends (JDBC and BDB) support appropriate bigints.

We might try adding a second Postgres backend for more recent versions of Postgres that support `ON CONFLICT`  although this would be new feature development (Someone interested enough would have to provide the resources for it)

There are ways to do this properly, but we have painted ourselves into a corner that makes those proper ways hard to reach.  I'll update the init code to use `real` instead of `float`.  The following command should change the schema of your existing DB.

````
ALTER TABLE tilepage ALTER COLUMN fill_factor TYPE real;
````

**Comment by emilzse** [comment]
I have been experiencing similar issue related to frequency_of_use

Solved by:
`ALTER TABLE tilepage ALTER COLUMN frequency_of_use TYPE real;`

> 2017-10-12 11:23:52,946 ERROR (GWC DiskQuota Updates Gathering Thread-2)[STDERR] org.springframework.dao.ConcurrencyFailureException: Failed to create or update page stats for page TilePage[demo#EPSG:4326#image/png@61,89,15] after 100 attempts
> 2017-10-12 11:23:52,946 ERROR (GWC DiskQuota Updates Gathering Thread-2)[STDERR]     at org.geowebcache.diskquota.jdbc.JDBCQuotaStore$9.upsertTilePageFillFactor(JDBCQuotaStore.java:564)
